locks: pi_multi-thread_locks.c
	gcc -o pi_multi-thread_locks pi_multi-thread_locks.c -lpthread
sermaphore: pi_multi-thread_sermaphore.c
	gcc -o pi_multi-thread_sermaphore pi_multi-thread_sermaphore.c -lpthread
clean:
	rm -r pi_multi-thread_locks pi_multi-thread_sermaphore